# Spin up the Aries Key Guardian service locally with DB
#
version: '3'

networks:
  kiva-network:
    external: true

services:
    aries-key-guardian:
    env_file:
      - ./.env
    build: ./
    command: npm run start:debug
    image: aries-key-guardian
    container_name: aries-key-guardian
    working_dir: /www
    ports:
      - "3003:3003"
      - "9228:9228"
    expose:
      - "3003"
    volumes:
      - ./:/www
    networks:
      - kiva-network
    tty: true
    depends_on: 
      - escrow-db

  escrow-db:
    image: postgres:11
    container_name: escrow-db
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs
    volumes:
      - ./logs/postgres:/logs:z
    env_file:
      - .env
    expose:
      - "5432"
    networks:
      - kiva-network
    tty: true
