# Spin up the Aries Key Guardian service locally with DB
#
version: '3.5'

networks:
  agency-network:
    external: true

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - agency-network
      
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - agency-network
    depends_on:
      - zookeeper 

  aries-key-guardian:
    env_file:
      - ./.env
    build: ./
    command: npm run start:debug
    image: aries-key-guardian
    container_name: aries-key-guardian
    working_dir: /www
    ports:
      - "3003:3003"
    expose:
      - "3003"
    volumes:
      - ./:/www
    networks:
      - agency-network
    tty: true
    depends_on:
      - escrow-db
  
  consumer:
    container_name: consumer-container
    image: aries-key-guardian-consumer
    build:
      context: ./
      dockerfile: Dockerfile.consumer
    tty: true
    networks: 
      - agency-network
    depends_on: 
      - kafka
      - zookeeper
      - escrow-db
      

  escrow-db:
    image: postgres:11
    container_name: escrow-db
    command: postgres
    env_file:
      - .env
    networks:
      - agency-network
    tty: true

# ----------LOCAL MODE----------
#
#version: '3.5'
#
#services:
#  escrow-db:
#    image: postgres:11
#    container_name: escrow-db
#    command: postgres
#    env_file:
#      - .env
#    tty: true
#    ports:
#      - 5432:5432
#    expose:
#      - 5432
