import { Column, Entity, Index, PrimaryGeneratedColumn, Unique } from 'typeorm';


@Unique(['external_id', 'external_id_type'])
@Entity()
export class ExternalId {

    /**
     * For simplicity we have an autogenerated integer id
     */
    @PrimaryGeneratedColumn()
    id: number;

    /**
     * The did of the entity this record refers to
     */
    @Index()
    @Column({ length: 32, unique: true })
    did: string;

    @Index()
    @Column({ type: 'text' })
    externalId: string;

    @Index()
    @Column({ type: 'text' })
    externalIdType: string;
}
