import { Entity, PrimaryGeneratedColumn, Column, Index } from 'typeorm';

@Entity()
export class WalletCredentials {

  /**
   * For simplicity we have an autogenerated integer id
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * Typically any of the authentication microservices will return a DID which can be used to look up the wallet data. All dids should be of length 32
   */
  @Index()
  @Column({ length: 32, unique: true })
  did: string;

  /**
   * Wallet ids are random unique uuids generated by the wallet server with the dashes stripped out
   */
  @Column({ length: 32 })
  wallet_id: string;

  /**
   * Wallet keys are randomly generated by the wallet server
   */
  @Column({ length: 32 })
  wallet_key: string;

  /**
   * Storing the seed here for convenience in case we need to regenerate DIDs in the future. We could store these in another table/db
   */
  @Column({ length: 32 })
  seed: string;
}
