# Required environment variables (set these in CircleCI):
# DOCKER_LOGIN - Dockerhub service account username
# DOCKER_PASSWORD - Dockerhub service account password

version: 2.1

jobs:
  build-and-test:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: cp dummy.env .env
      - run: echo $TWILIOENV | base64 --decode >> .env
      - run: npm install nodemon --save-dev
      - run: npm install
      - run: docker-compose -f docker-compose.ci.yml build
      - run:
          name: Start docker compose and wait for readiness
          command: |
              set -x
              docker-compose -f docker-compose.ci.yml up -d
              sleep 150
              docker-compose -f docker-compose.ci.yml logs
#     - run: docker exec -it aries-key-guardian npm run test
      - run:
          name: SKIPPING TESTS. TODO: fix the unit tests
          command: echo "SKIPPING TESTS"



workflows:
  build-test-deploy:
    jobs:
      - build-and-test:
          filters: # run for all branches AND tags
              tags:
                  only: /.*/
      - docker/publish:
          requires:
              - build-and-test
          filters: # only run for semver tagged versions
              tags:
                  only: /^([0-9]+)\.([0-9]+)\.([0-9]+)/
              branches:
                  ignore: /.*/
          update-description: true
          dockerfile: Dockerfile.production
          image: kivaprotocol/aries-key-guardian
          tag: << pipeline.git.tag >>

orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.3.0
