import typeorm from 'typeorm';

@typeorm.Unique(['external_id', 'external_id_type'])
@typeorm.Entity()
export class ExternalId {

    /**
     * For simplicity we have an autogenerated integer id
     */
    @typeorm.PrimaryGeneratedColumn()
    id: number;

    /**
     * The agentId of the entity this record refers to
     */
    @typeorm.Index()
    @typeorm.Column({ length: 32, unique: true })
    agent_id: string;

    /**
     * The value of the external id referenced by this row (e.g. NIN55555).
     */
    @typeorm.Index()
    @typeorm.Column({ type: 'text' })
    external_id: string;

    /**
     * The type of external id referenced by this row (e.g. sl_national_id)
     */
    @typeorm.Index()
    @typeorm.Column({ type: 'text' })
    external_id_type: string;
}
