import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';

@Entity()
export class SmsOtp {

    /**
     * For simplicity we have an autogenerated integer id
     */
    @PrimaryGeneratedColumn()
    id: number;

    /**
     * The agentId of the entity this record hold the phone number for
     */
    @Column({ length: 32, unique: true })
    agentId: string;

    /**
     * First 32 bytes of SHA256 hash of phone number
     */
    @Column({ length: 32, nullable: true })
    phone_number_hash: string;

    /**
     * 6-digit OTP
     */
    @Column({ nullable: true })
    otp: number;

    /**
     * Time when OTP is no longer valid
     */
    @Column({ type: 'timestamp without time zone', nullable: true })
    otp_expiration_time: Date;
}
