apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
  {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
  {{- end }}
      containers:
      - args:
        name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom:
        - secretRef:
            name: {{ .Values.secrets }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: {{ .Values.service.portName }}
            containerPort: {{ .Values.service.containerPort }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.readiness.timeoutSeconds }}
          httpGet:
            path: {{ .Values.readiness.path }}
            port: {{ .Values.service.containerPort }}
            httpHeaders:
            - name: x-request-id
              value: k8s-healthz
        livenessProbe:
          initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.liveness.timeoutSeconds }}
          httpGet:
            path: {{ .Values.liveness.path }}
            port: {{ .Values.service.containerPort }}
            httpHeaders:
            - name: x-request-id
              value: k8s-healthz
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        {{- with .Values.image.imagePullSecrets }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
